# Generated by Django 2.1.2 on 2018-11-06 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='comments_count',
        ),
    ]
